apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: foresporsel-om-deling-av-cv-api
  namespace: toi
  labels:
    team: toi
spec:
  groups:
    - name: foresporsel-om-deling-av-cv-api
      rules:
        - alert: foresporsel-om-deling-av-cv-api
          expr: kube_deployment_status_replicas_available{deployment="foresporsel-om-deling-av-cv-api"} == 0
          for: 1s
          annotations:
            summary: Appen er nede
            action: "https://logs.az.nav.no/goto/0b232af0e9b0d5a0f67716fe630469e4?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: foresporsel-om-deling-av-cv-api
          expr: sum(increase(log_messages_errors{app="foresporsel-om-deling-av-cv-api", level="Error"}[10m])) > 0
          for: 1s
          annotations:
            summary: Appen har logget en error
            action: "https://logs.az.nav.no/goto/0b232af0e9b0d5a0f67716fe630469e4?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: critical

        - alert: foresporsel-om-deling-av-cv-api
          expr: sum(increase(log_messages_errors{app="foresporsel-om-deling-av-cv-api", level="Warning"}[10m])) > 3
          for: 1s
          annotations:
            summary: Økning i warnings
            action: "https://logs.az.nav.no/goto/0b232af0e9b0d5a0f67716fe630469e4?security_tenant=navlogs"
          labels:
            namespace: toi
            severity: warning
