apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: foresporsel-om-deling-av-cv-api
  namespace: arbeidsgiver-inkludering
  labels:
    team: arbeidsgiver-inkludering
spec:
  receivers:
    slack:
      channel: 'inkludering-alerts-prod'
  alerts:
    - alert: 'foresporsel-om-deling-av-cv-api'
      expr: sum(up{app="foresporsel-om-deling-av-cv-api", job="kubernetes-pods"}) == 0
      for: 1s
      description: "Appen er nede"
      action: "https://logs.adeo.no/goto/ab2e52186c18abccf8a98e0ec87eb85c"

    - alert: 'foresporsel-om-deling-av-cv-api'
      expr: sum(increase(logd_messages_total{log_app="foresporsel-om-deling-av-cv-api",log_level="Error"}[10m])) > 0
      for: 10s
      description: "Appen har logget en feil"
      action: "https://logs.adeo.no/goto/ab2e52186c18abccf8a98e0ec87eb85c"
