apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: foresporsel-om-deling-av-cv-api
  namespace: arbeidsgiver-inkludering
  labels:
    team: arbeidsgiver-inkludering
spec:
  image: {{ image }}
  port: 8333
  vault:
    enabled: true
  ingresses:
  {{#each ingress as |url|}}
     - {{ url }}
  {{/each}}
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  webproxy: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand-container
          namespace: toi
          cluster: {{ gcp-cluster }}
        - application: rekrutteringsbistand-kandidat-api
          namespace: toi
          cluster: {{ fss-cluster }}
  kafka:
    pool: {{ kafka-pool }}
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{ kafka_consumer_group_id }}
    - name: KAFKA_RESET_POLICY
      value: "earliest"
