apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: foresporsel-om-deling-av-cv-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 8333
  vault:
    enabled: true
  ingresses:
  {{#each ingress as |url|}}
     - {{ url }}
  {{/each}}
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  webproxy: true
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - NAVident
        groups:
          - id: {{ ad_gruppe_modia_generell_tilgang }}
          - id: {{ ad_gruppe_jobbsokerrettet }}
          - id: {{ ad_gruppe_arbeidsgiverrettet }}
          - id: {{ ad_gruppe_utvikler }}
  accessPolicy:
    inbound:
      rules:
        - application: rekrutteringsbistand
          namespace: toi
          cluster: {{ gcp-cluster }}
        - application: rekrutteringsbistand-frontend
          namespace: toi
          cluster: {{ gcp-cluster }}
        - application: rekrutteringsbistand-kandidat-api
          namespace: toi
          cluster: {{ fss-cluster }}
  kafka:
    pool: {{ kafka-pool }}
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{ kafka_consumer_group_id }}
    - name: KAFKA_RESET_POLICY
      value: "latest"
    - name: REKRUTTERINGSBISTAND_JOBBSOKERRETTET
      value: {{ad_gruppe_jobbsokerrettet}}
    - name: REKRUTTERINGSBISTAND_ARBEIDSGIVERRETTET
      value: {{ad_gruppe_arbeidsgiverrettet}}
    - name: REKRUTTERINGSBISTAND_UTVIKLER
      value: {{ad_gruppe_utvikler}}
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
      enabled: true
