apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: foresporsel-om-deling-av-cv-api
  namespace: arbeidsgiver-inkludering
  labels:
    team: arbeidsgiver-inkludering
spec:
  image: {{image}}
  port: 8333
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
